name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_PROJECT: winter-cocoa-335403 
  GCR_IMAGE: app-cd-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build app-cd-test image
        run: |
          docker build --file Dockerfile \
          -t "gcr.io/$GCP_PROJECT/$GCR_IMAGE:$GITHUB_SHA" \
          -t "gcr.io/$GCP_PROJECT/$GCR_IMAGE:${{ github.SHA }}" \
          .
      - name: Set up cloud sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Login and publish image
        run: |
          gcloud auth configure-docker -q
          docker push --all-tags "gcr.io/$GCP_PROJECT/$GCR_IMAGE"

  
