name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_PROJECT: acesso-infrasec-prod
  GCR_IMAGE: app-cd-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build app-cd-test image
        run: |
          docker build --file Dockerfile \
          -t "gcr.io/$GCP_PROJECT/$GCR_IMAGE:$GITHUB_SHA" \
          -t "gcr.io/$GCP_PROJECT/$GCR_IMAGE:${{
